# Generated by Django 4.1.4 on 2023-03-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_scrapbook_topic_delete_discover_scrapbook_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrapbook',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
