# Generated by Django 4.1.4 on 2023-02-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_image_alter_profile_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
