# Generated by Django 4.1.4 on 2023-02-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='pic',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
    ]
