# Generated by Django 4.1.4 on 2023-02-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_image_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(default='blank.png', null=True, upload_to='img/%y'),
        ),
    ]
