# Generated by Django 4.1.4 on 2023-02-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_image_caption_image_job_alter_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='caption',
        ),
    ]
