# Generated by Django 4.1.4 on 2023-01-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_on',
        ),
    ]
