# Generated by Django 4.1.4 on 2023-01-24 08:36

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0003_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=django_fields.fields.DefaultStaticImageField(blank=True, default='blank.png', null=True, upload_to=''),
        ),
    ]
