# Generated by Django 4.1.4 on 2023-01-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0004_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='post_pics'),
        ),
    ]
