# Generated by Django 4.1.4 on 2023-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0008_alter_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='blank.png', null=True, upload_to='scrapbook/post_pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
