# Generated by Django 4.1.4 on 2023-01-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0009_photo_remove_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='scrapbook/post_pics'),
        ),
    ]
