# Generated by Django 4.1.4 on 2023-01-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0010_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
