# Generated by Django 4.1.4 on 2023-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0013_rename_photo_image_rename_photo_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='scrapbook.image'),
        ),
    ]
