# Generated by Django 4.1.4 on 2023-01-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0016_remove_posts_image_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='media/'),
        ),
    ]
