# Generated by Django 4.1.4 on 2023-01-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0020_remove_scrapbook_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapbook',
            name='topic',
        ),
        migrations.AddField(
            model_name='posts',
            name='scrapbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapbook.scrapbook'),
        ),
    ]
