# Generated by Django 4.1.4 on 2023-01-27 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0022_select_scrapbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbook',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapbook.topic'),
        ),
    ]
