# Generated by Django 4.1.4 on 2023-01-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_scrapbook_topic_delete_discover_scrapbook_topic'),
        ('scrapbook', '0023_scrapbook_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='scrapbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discover.scrapbook'),
        ),
        migrations.DeleteModel(
            name='Scrapbook',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
