# Generated by Django 4.1.4 on 2023-03-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0024_alter_posts_scrapbook_delete_scrapbook_delete_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scrapbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapbook.topic')),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='scrapbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapbook.scrapbook'),
        ),
    ]
