# Generated by Django 4.1.4 on 2023-03-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0025_topic_scrapbook_alter_posts_scrapbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapbook',
            old_name='name',
            new_name='title',
        ),
    ]
