# Generated by Django 4.1.4 on 2023-03-24 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0026_rename_name_scrapbook_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapbook',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapbook.topic'),
        ),
    ]
