# Generated by Django 4.1.4 on 2023-03-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0032_alter_scrapbook_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='blank.png', null=True, upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='scrapbook',
            name='cover',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='media/', verbose_name='CoverImage'),
        ),
    ]
