# Generated by Django 4.1.4 on 2023-03-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0034_alter_scrapbook_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoverImage',
        ),
        migrations.AlterField(
            model_name='scrapbook',
            name='cover',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='media/', verbose_name='Image'),
        ),
    ]
